version: 2
jobs:
  make_groups:
    docker:
      - image: buildpack-deps:bionic-scm

    working_directory: ~/repo

    steps:
      - run:
          name: Install base apt packages
          command: |
            apt-get update --yes -qq
            apt-get install --yes -qq python3 python3-venv jq git-crypt

      - checkout

      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "requirements.txt" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run:
          name: install dependencies
          command: |
            python3 -m venv venv
            source venv/bin/activate
            pip install --upgrade -r requirements.txt
            echo 'export PATH="${HOME}/repo/venv/bin:$PATH"' >> ${BASH_ENV}

      - save_cache:
          paths:
            - ./venv
          key: v1-dependencies-{{ checksum "requirements.txt" }}

      - run:
          name: unlock secrets
          command: |
            echo "${GIT_CRYPT_KEY}" | base64 -d > ~/repo/key
            git crypt unlock ~/repo/key
            rm ~/repo/key

      - run:
          # these should be split into parallel jobs
          # TODO: how to parameterize input files?
          name: create calgroups
            environment:
              GROUPER_BASE_URI: https://calgroups.berkeley.edu/gws/servicesRest/json/v2_2_100
          command: |
            for course in courses/*json ; do
              echo ${course}
              jq -r '.[] | [ .year, .semester, .class ] | @sh' < ${course} | \
                xargs -n 3 ./make-groups.sh
            done

#workflows:
#  version: 2
#  daily:
#    triggers:
#      - schedule:
#          # 4a PST is 11a UTC
#          cron: "0 11a * * *"
#          filters:
#            branches:
#              only:
#                - master
#    jobs:
#      - make_groups
